Dev
prvsega/RestApiEmployee pull request #1
Opened 2023-01-17 13:59 UTC by prvsega

new feature implemented. Everything works correctly.

2023-01-17 14:01 UTC, prvsega commented
[add Validation Employee and class ExceptionHandler]
[created package Mappers with classes and moved convert-methods. corrected bugs field names (manytomany). add new functional about roles]

2023-01-18 08:17 UTC, Alex-javac requested changes
исправь эти мелочи. а в целом норм

2023-01-18 08:17 UTC, Alex-javac commented on src/main/java/by/prvsega/restservice/RespApiServiceApplication.java
> +    @Bean
вынеси бин из этого класса. создай MapperConfig и помести его туда

2023-01-18 08:17 UTC, Alex-javac commented on src/main/java/by/prvsega/restservice/contollers/EmployeeController.java
> +    private final EmployeeMapper employeeMapper;
В контроллере не должно быть маперов перенеси его в сервис.

2023-01-18 08:17 UTC, Alex-javac commented on src/main/java/by/prvsega/restservice/contollers/RoleController.java
> +public class RoleController {
этот контролер вообще не нужен.

2023-01-18 08:17 UTC, Alex-javac commented on src/main/java/by/prvsega/restservice/models/Employee.java
> +@ToString
@Data содержит в себе @ToString

2023-01-18 08:17 UTC, Alex-javac commented on src/main/java/by/prvsega/restservice/models/Employee.java
> +@ToString
Вместо @Data укажи что тебе нужно например:
@Getter
@Setter
@NoArgsConstructor

2023-01-18 08:17 UTC, Alex-javac commented on src/main/java/by/prvsega/restservice/models/Employee.java
> +    @ManyToMany
Почитай про fetchtype.eager и fetchtype.lazy подумай как их использовать и тогда победишь рекурсию))

2023-01-18 08:17 UTC, Alex-javac commented on src/main/java/by/prvsega/restservice/services/EmployeeService.java
>      @Autowired
раз ты уже используешь ломбок то вместо конструктора можно использовать на классом @RequiredArgsConstructor(onConstructor = @__(@Autowired))
вместо конструктора

2023-01-18 08:17 UTC, Alex-javac commented on src/main/java/by/prvsega/restservice/services/EmployeeService.java
> -
совсем нет проверок. что будет если вместо id  будет null?

2023-01-18 08:17 UTC, Alex-javac commented on src/main/java/by/prvsega/restservice/services/EmployeeService.java
> -
ну и во всех остальных также

2023-01-23 06:27 UTC, Alex-javac approved these changes
исправь и слей

2023-01-23 06:27 UTC, Alex-javac commented on src/main/java/by/prvsega/restservice/config/MapperConfig.java
> +public class MapperConfig {
используй @Configuration

2023-01-23 06:27 UTC, Alex-javac commented on src/main/java/by/prvsega/restservice/services/EmployeeService.java
> +        return employeeMapper.converterToDTO(employeeRepository.findById(id).orElseThrow(EmployeeNotFoundException::new));
если id null обращение в бд не делай. сразу кинь exception

2023-01-23 06:27 UTC, Alex-javac commented on src/main/java/by/prvsega/restservice/models/Role.java
> +    @ManyToMany(mappedBy = "rolesSet")
используй  fetchtype.lazy

2023-01-23 06:27 UTC, Alex-javac commented on src/main/java/by/prvsega/restservice/services/EmployeeService.java
> +    public void sendEmailAboutRegistration(Employee employee) {
сделай метод универсальным передай туда email  и massage

2023-01-23 06:27 UTC, Alex-javac commented on src/main/java/by/prvsega/restservice/services/EmployeeService.java
> +    public void sendEmailAboutRegistration(Employee employee) {
и вынеси его в майл сервис

2023-01-23 07:50 UTC, merged